app.name = ComputerPresence

app.error.noBotId = Please pass command line parameter '-id' or set the system property 'discord.botId' to a valid value.
app.error.noPresenceFile = Please pass command line parameter '-file' or set the system property 'presence.file' to a valid value.
app.error.notLockOwner = An instance of %s is already running, do you wish to run another instance?
app.error.discordNotOpen = It appears that Discord is not open on your computer. %s will now be shutting down.
app.error.init = Uncaught exception while initializing!
app.error.tick = Uncaught exception while running!
app.error.reload = Uncaught exception while reloading presence script!
app.error.edit = Uncaught exception while attempting to open script editor!
app.error.reload.notFound = Presence file doesn't exist anymore!

app.dialog.error.footer = Continue running?
app.dialog.error.continue = Continue
app.dialog.error.reload = Reload Script
app.dialog.error.exit = Exit
app.dialog.error.okay = Okay

app.firstRunWarning = You are running %1$s for the first time. This application will monitor EVERYTHING you do on your \
  computer and broadcast it as a Discord activity.\n\
  This will monitor:\n\
  - Programs Open\n\
  - Processes Running\n\
  - System Uptime\n\
  - Computer Idle Time\n\
  - Miscellaneous System Information\n\
  You can change how ComputerPresence behaves in %2$s\n\
  \n\
  DISCLAIMER: The Lua used in %1$s is NOT sandboxed, and it can arbitrarily run executable code with \
  full access to your computer.\n\
  \n\
  Do you still wish to run %1$s?

app.popup.enabled = Enabled?
app.popup.script.reload = Reload Script
app.popup.script.edit = Edit Script
app.popup.exit = Exit
app.popup.licenses = Licenses

license.errors.desktop = <html><body><p>Opening files in this platform is not supported. </p>\
  <a href=%s>Please open it yourself &lt;-&gt;</a></body></html>
license.errors.generic = Error displaying license report: %s